title: PocketJS
email: your-email@example.com
description: >
  Aprendendo a programar com pequenas doses de JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pocketjs.com.br" # the base hostname & protocol for your site, e.g. http://example.com
analytics: UA-20338334-13

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
sass:
  sass_dir: assets/_sass
  style: compressed